model_name: QHFlow_so2_v5_1
version: QHFlow_so2_v5_1

hidden_size: 64
bottle_hidden_size: 32
use_block_S: True
use_block_H: True
num_gnn_layers: 3
num_ham_gnn_layers: 2
basis: def2-svp-nabla
max_radius: 25
max_num_neighbors: 64
